### ISSUE TITLE
Use JuMP with custom version Ipopt

### ISSUE THREAD

**Issue by TPDS1993** [JuliaOpt/Ipopt.jl#100]
Hi,

I already use JuMP with the Ipopt package, but my superior gave me other linear solvers, like MA57, MA77 and others, and I wanted to use them. I already have a separate Ipopt installation from the official website, and now I wanted to use Ipopt.jl with my already installed and precompiled Ipopt... How could I do that?

Thanks in advance.

**Comment by mlubin** [comment]
Answered at https://discourse.julialang.org/t/use-ipopt-with-custom-version/. In the future, please link when you cross-post a question.
