### ISSUE TITLE
Pkg.build("Ipopt") failed on windows 10

### ISSUE THREAD

**Issue by Ellie-Peng** [JuliaOpt/Ipopt.jl#107]
I am using Julia 0.6.2 and want to install Ipopt package, however, then I got this error message:

> LoadError: MethodError: no method matching BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::Array{String,1}, ::Symbol)
> Closest candidates are:
>   BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::Array{S<:AbstractString,1}) where S<:AbstractString at C:\Users\p\AppData\Local\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\BinaryProvider\src\Products.jl:42
>   BinaryProvider.LibraryProduct(::BinaryProvider.Prefix, ::AbstractString) at C:\Users\p\AppData\Local\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\BinaryProvider\src\Products.jl:38
>   BinaryProvider.LibraryProduct(::AbstractString, ::Array{S<:AbstractString,1}) where S<:AbstractString at C:\Users\p\AppData\Local\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\BinaryProvider\src\Products.jl:56
> while loading C:\Users\p\AppData\Local\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Ipopt\deps\build.jl, in expression starting on line 13

**UndefVarError: BinaryProvider not defined**

**Comment by superboal** [comment]
Did you ever figure out how to fix this?

**Comment by odow** [comment]
Try running `Pkg.update()` and then `Pkg.build("Ipopt")`.

You may also want to try removing and adding it again.
```
Pkg.rm("Ipopt")
Pkg.update()
Pkg.add("Ipopt")
```

**Comment by dpsanders** [comment]
Alan Edelman reported the same problem on Mac:

```
INFO: Installing Ipopt v0.3.0
INFO: Installing MathProgBase v0.7.1
INFO: Building Ipopt
WARNING: imported binding for srcdir overwritten in module __anon__
Info: Downloading https://github.com/staticfloat/IpoptBuilder/releases/download/v3.12.8-9/Ipopt.x86_64-apple-darwin14.tar.gz to /Users/edelman/.julia/v0.6/Ipopt/deps/usr/downloads/Ipopt.x86_64-apple-darwin14.tar.gz...
================================[ ERROR: Ipopt ]================================

LoadError: BinaryProvider.LibraryProduct("/Users/edelman/.julia/v0.6/Ipopt/deps/usr/lib", String["libipopt"], :libipopt, "Prefix(/Users/edelman/.julia/v0.6/Ipopt/deps/usr)") is not satisfied, cannot generate deps.jl!
while loading /Users/edelman/.julia/v0.6/Ipopt/deps/build.jl, in expression starting on line 13

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Ipopt had build errors.

 - packages with build errors remain installed in /Users/edelman/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Ipopt")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated


julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

```

**Comment by dpsanders** [comment]
Looks like it works on Julia 0.6.2 but not Julia 0.6.0!

**Comment by Ellie-Peng** [comment]
After update and add package again, it works
