### ISSUE TITLE
Option to omit printing Ipopt header information

### ISSUE THREAD

**Issue by juliohm** [JuliaOpt/Ipopt.jl#112]
Even though I've been using `IpoptSolver(print_level=0)`, I still get this header printed on the first run:

```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************
```

Is there any way to omit this information?

**Comment by odow** [comment]
Not to my knowledge. The list of options that can be passed to Ipopt is [here](https://www.coin-or.org/Ipopt/documentation/node41.html).

You could use [redirect_stdout](https://docs.julialang.org/en/stable/stdlib/io-network/#Base.redirect_stdout) as suggested [here](https://github.com/JuliaOpt/JuMP.jl/issues/325#issuecomment-64974955), but if you are distributing the code, I'm not sure of the licence implications.

**Comment by mlubin** [comment]
No, it's baked into the code (https://github.com/coin-or/Ipopt/blob/27f645c0ce7207fc589116c2b489df23f0196a40/Ipopt/src/Algorithm/IpIpoptAlg.cpp#L956). You can modify the source if you like.

**Comment by juliohm** [comment]
Wow, baked in the code, unbelievable. I would never do that to my users.

Thank you for pointing to the source code where this annoying message lies.

**Comment by mlubin** [comment]
Actually, a bit more digging reveals there's an undocumented option to suppress this warning. `IpoptSolver(sb="yes")` does the trick for me. TIL.

**Comment by juliohm** [comment]
Good catch! Works like a charm, maybe add to a FAQ? I am sure other people would feel happy about it.

**Comment by mlubin** [comment]
Not sure about that. It could be perceived as disregarding the authors' intentions. I'd first want to see a discussion of this on the Ipopt mailing list.

**Comment by odow** [comment]
Just to follow up: this came up in a discussion I had with Andreas. He intentionally made the option obscure and undocumented. We won't be adding this to the FAQ, or advertising it too widely.

**Comment by juliohm** [comment]
This is not necessarily a smart move. You will just get more annoying issues asking for this feature.

**Comment by odow** [comment]
> contact the author of Ipopt

Andreas is the author of Ipopt.

**Comment by juliohm** [comment]
And he prefers to enforce the message on users? Ok then.
