### ISSUE TITLE
Consistent build error on Travis CI Linux

### ISSUE THREAD

**Issue by juliohm** [JuliaOpt/Ipopt.jl#125]
The build is successful on Mac OS, but fails consistently on Linux: https://travis-ci.org/juliohm/ExtremeStats.jl/jobs/398913447

Any advise on how to fix the build is appreciated.

**Comment by tkelman** [comment]
Your package's `.travis.yml` needs
https://github.com/JuliaOpt/Ipopt.jl/blob/4fba47df3cbd7e4302bbd31412ab15d7d4b9d7fb/.travis.yml#L11-L13

Or if BinaryBuilder can fix its requirement that Julia itself is built using the same version of gcc as BinaryBuilder uses (ref https://github.com/JuliaOpt/Ipopt.jl/blob/4fba47df3cbd7e4302bbd31412ab15d7d4b9d7fb/deps/build.jl#L5-L7), then that could be used here.

**Comment by juliohm** [comment]
Thank you @tkelman, is there an issue open already in BinaryBuilder.jl regarding the GCC version? Your suggestion fixed my build on Travis :+1:

**Comment by juliohm** [comment]
Thanks, I am closing this one.
