### ISSUE TITLE
Unsatisfiable requirements between JuMP, MOI, & Ipopt

### ISSUE THREAD

**Issue by rbharvs** [JuliaOpt/Ipopt.jl#129]
Hi, as I understand it, `Ipopt v0.4.0` supports `MOI` (https://github.com/JuliaOpt/Ipopt.jl/releases). However, `Ipopt` requires `MOI v0.4.0`, whereas the `master` branch of `JuMP` requires `MOI v0.5.0` or above. Thus, when I `add JuMP#master` in the package manager, it bumps `Ipopt` to `v0.3.0` rendering it unusable with `JuMP`.

**Comment by mlubin** [comment]
I just attempted to update Ipopt for MOI 0.5, but it's blocked by https://github.com/JuliaOpt/MathOptInterface.jl/issues/463 and https://github.com/JuliaOpt/MathOptInterface.jl/pull/467.

**Comment by mlubin** [comment]
Update: I have a local branch passing tests on MOI 0.6, so just need to wait until that's released.
