### ISSUE TITLE
Ipopt fails on simple constr. opt. problem

### ISSUE THREAD

**Issue by arbenede** [JuliaOpt/Ipopt.jl#132]
The repo at https://github.com/arbenede/error_reports.git contains contains some code to solve a simple nonlinearly constrained optimization problems that fails under both Windows and Linux (Windows log is in the repo). The Linux error file was posted a few days ago by @tkoolen at https://gist.github.com/tkoolen/79071106c93e3c974cdb11f5a44269df. Apparently it works under OSX (see the thread at https://discourse.julialang.org/t/jump-ipopt-failing-on-simple-problem/13209 )

**Comment by mlubin** [comment]
The error message (for reference below) indicates the crash is inside mumps, which is a linear algebra library that Ipopt depends on. The issue may or may not be related to the Julia wrapper, but it's a pretty significant task to debug. You may have more luck on the Ipopt user mailing list (https://list.coin-or.org/mailman/listinfo/ipopt).

CC @svigerske


```
Exception: EXCEPTION_ACCESS_VIOLATION at 0x684eb7bc -- dmumps_454_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
while loading C:\Users\arbenede\projects\Frequency_Domain_ToF\julia\test_IPopt.jl, in expression starting on line 34
dmumps_454_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
dmumps_559_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
dmumps_203_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
dmumps_26_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
dmumps_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
dmumps_f77_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
dmumps_c at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libcoinmumps-1.dll (unknown line)
ZN5Ipopt20MumpsSolverInterface21SymbolicFactorizationEv at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt20MumpsSolverInterface10MultiSolveEbPKiS2_iPdbi at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt16TSymLinearSolver10MultiSolveERKNS_9SymMatrixERSt6vectorINS_8SmartPtrIKNS_6VectorEEESaIS8_EERS4_INS5_IS6_EESaISC_EEbi at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt18StdAugSystemSolver10MultiSolveEPKNS_9SymMatrixEdPKNS_6VectorEdS6_dPKNS_6MatrixES6_dS9_S6_dRSt6vectorINS_8SmartPtrIS5_EESaISC_EESF_SF_SF_RSA_INSB_IS4_EESaISG_EESJ_SJ_SJ_bi at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt15AugSystemSolver5SolveEPKNS_9SymMatrixEdPKNS_6VectorEdS6_dPKNS_6MatrixES6_dS9_S6_dRS5_SA_SA_SA_RS4_SB_SB_SB_bi at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt22LowRankAugSystemSolver5SolveEPKNS_9SymMatrixEdPKNS_6VectorEdS6_dPKNS_6MatrixES6_dS9_S6_dRS5_SA_SA_SA_RS4_SB_SB_SB_bi at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt22LeastSquareMultipliers20CalculateMultipliersERNS_6VectorES2_ at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt25DefaultIterateInitializer18least_square_multsERKNS_10JournalistERNS_8IpoptNLPERNS_9IpoptDataERNS_25IpoptCalculatedQuantitiesERKNS_8SmartPtrINS_22EqMultiplierCalculatorEEEd at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt25DefaultIterateInitializer18SetInitialIteratesEv at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt14IpoptAlgorithm18InitializeIteratesEv at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt14IpoptAlgorithm8OptimizeEb at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt16IpoptApplication13call_optimizeEv at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt16IpoptApplication11OptimizeNLPERKNS_8SmartPtrINS_3NLPEEERNS1_INS_16AlgorithmBuilderEEE at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt16IpoptApplication11OptimizeNLPERKNS_8SmartPtrINS_3NLPEEE at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
ZN5Ipopt16IpoptApplication12OptimizeTNLPERKNS_8SmartPtrINS_4TNLPEEE at C:\Users\arbenede\.julia\v0.6\Ipopt\deps\usr\bin\libipopt-1.dll (unknown line)
```

**Comment by tkelman** [comment]
Try writing the problem to a .nl file with AmplNLWriter and see if it can be reproduced outside Julia with just ipopt.exe?

**Comment by arbenede** [comment]
A temporary fix was found by adding the "start=" argument when defining the optimization variables, see the discussion at https://discourse.julialang.org/t/jump-ipopt-failing-on-simple-problem/13209/3

**Comment by mlubin** [comment]
The default starting point is 0 (http://www.juliaopt.org/JuMP.jl/0.18/nlp.html#nonlinear-modeling), and `atan(0, 0)` (present in the constraints) is not differentiable so I would expect some trouble from Ipopt but not a segfault.

**Comment by svigerske** [comment]
I think that Ipopt by default doesn't check derivatives for NaN's and inf's. One can enable such a check by an option: https://www.coin-or.org/Ipopt/documentation/node44.html#SECTION000114030000000000000
Ipopt expects that the eval callbacks return false if a function or its derivatives cannot be evaluated, so maybe something in the JuMP/Ipopt interface or domain violation handling of the AD doesn't work? In this case where the starting point is non-differentiable, one should have obtained some nice error message from Ipopt.
That Mumps is segfaulting here is not nice, too.
So, I think I can pass the buck away from Ipopt. :)

**Comment by mlubin** [comment]
@svigerske thanks for that pointer. It looks like we're not handling NaNs and Infs correctly in the wrapper.
