### ISSUE TITLE
Using Ipopt with Jump in Julia v0.7.0 fails

### ISSUE THREAD

**Issue by HamletFr** [JuliaOpt/Ipopt.jl#134]
I am trying to use JuMP and Ipopt under Julia v0.7.0. When I try to construct a model:

```julia
julia> m = Model(solver=IpoptSolver())
I get the following error message:

Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver is Error showing value of type Model:
ERROR: BoundsError: attempt to access 1-element Array{SubString{String},1} at index [2]
I am using the following versions of the packages:

```
Ipopt v0.4.0
JuMP v0.18.2

Any ideas? Thanks!

This is a cross post from https://stackoverflow.com/questions/51908147/error-with-jump-and-ipopt

**Comment by blegat** [comment]
JuMP v0.18.2 does not support Julia v0.7, see [this post](https://discourse.julialang.org/t/jump-and-julia-0-7-1-0/12964/5)
