### ISSUE TITLE
bug on julia 1.0 if restoration error or something similar

### ISSUE THREAD

**Issue by Wikunia** [JuliaOpt/Ipopt.jl#144]
This line is not working on Julia v1 as `warn(` is deprecated in v0.7
https://github.com/JuliaOpt/Ipopt.jl/blob/master/src/MPBWrapper.jl#L168

Unfortunately simply changing it to `@warn` doesn't solve the problem as it breaks on julia v0.6

**Comment by mlubin** [comment]
The `Compat` package provides `@warn` on 0.6.

**Comment by Wikunia** [comment]
I thought so but my tests on travis didn't pass:
https://travis-ci.org/Wikunia/Ipopt.jl/jobs/438050324#L3447
