### ISSUE TITLE
How to suppress the output when used in JuMP?

### ISSUE THREAD

**Issue by tamasgal** [JuliaOpt/Ipopt.jl#162]
During the prototype phase I like to examine the output and used `Ipopt` like this:

```
model = Modle(with_optimizer(Ipopt.Optimizer))
```

I found here https://github.com/JuliaOpt/Ipopt.jl/issues/93 that one can suppress the output, but the `solver=` keyword does not exist anymore and I don't find anywhere how to pass `print_level=0` to the `Optimizer`.

So how do I suppress the output?

**Comment by tamasgal** [comment]
Classic, just found it: https://github.com/JuliaOpt/JuMP.jl/blob/c01802926c34aa30e5d272ac1063f1595084aa4a/examples/rosenbrock.jl#L15

```
model = Model(with_optimizer(Ipopt.Optimizer, print_level=0))
```

**Comment by pierre-haessig** [comment]
For those arriving on this old issue from a search engine:

- `with_optimizer` was [deprecated in JuMP 0.21](https://jump.dev/JuMP.jl/stable/release_notes/#Version-0.21.0-(Feb-16,-2020)) (released in Feb 2020) and is now removed.  See also the [Models/Solver options](https://jump.dev/JuMP.jl/stable/manual/models/#solver_options) section of the manual.
- for suppressing Ipopt output, [`set_silent(model)`](https://jump.dev/JuMP.jl/stable/manual/models/#Turn-off-output) works.
