### ISSUE TITLE
Acessing constraint dual value

### ISSUE THREAD

**Issue by Schepy** [JuliaOpt/Ipopt.jl#171]
I have the same test optimization model in GAMS and Julia.

GAMS using Ipopt calculates dual values of constraints normally and in Julia I get error:
"ArgumentError: ModelLike of type Ipopt.Optimizer does not support accessing the attribute MathOptInterface.ConstraintDual(1)"

**Comment by mlubin** [comment]
Does your model have quadratic constraints? It looks like duals on quadratic constraints may have been unintentionally omitted from the interface.

**Comment by Schepy** [comment]
Yes it does. In fact, I am trying to access such duals. :)

**Comment by mlubin** [comment]
As a temporary workaround you can use `@NLconstraint` instead of `@constraint`.

**Comment by Schepy** [comment]
I wish to supply additional information regarding constraint.

My constraint is of a form: x = (y-z)^2
which is of non-convex quadratic type due to equality.

I have relaxed the constraint into x >= (y-z)^2
to make it convex and to test if this issue's problem still persists and it does. So, the issue is still valid.
NLconstraint works for duals as suggested.

Besides of dual command problem, I have the following two groups of questions.
Any insight into my questions is greatly welcomed.

Regarding my original constraint x = (y-z)^2,
how is it better to model it (performance wise, ignoring dual value problem)?
Is it better to use NLconstraint or constraint? What is the difference between two?
Why does even "constraint" work since equality constraint is not convex?

During Ipopt solution process, its current objective function jumps up and down in value a lot on difficult problems and sometimes never converges (my observation). This is very different from what I can see in Gurobi (constraints relaxed in convex ">=" ) where objective function changes continuously. Is it true that even on convex problems Ipopt does not guarantee convergence at all, while I think Gurobi does in polynomial time, even thou both use interior point algorithm?
