### ISSUE TITLE
Termination status globally solved

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaOpt/Ipopt.jl#180]
Is there a way to find out, if an optimization problem has found a global optimum when using `Ipopt` and `JuMP` just by analysing the returned results from a model. Because `terminal_status` returns `LOCALLY_SOLVED::TerminationStatusCode = 4` also for global minima.

**Comment by blegat** [comment]
`OPTIMAL` is never returned:
https://github.com/JuliaOpt/Ipopt.jl/blob/5706171050abdf6e7917c2f04228c2d7076fc292/src/MOI_wrapper.jl#L847-L889
As Ipopt only has blackbox callbacks to the objective function, it has no way to determine whether it is a global solution or not. You would need for instance to additionally have Lipschitz continuity of the objective function and a bounded domain to make sure the place you've not looked at does not contain any better solution (using a sort of branch and bound excluding part of the state space thanks to the Lipschitz constant and existing good solutions).

**Comment by ueliwechsler** [comment]
Thanks for the clarification and the reference.
