### ISSUE TITLE
Version considerations after MOI 0.9

### ISSUE THREAD

**Issue by Libbum** [JuliaOpt/Ipopt.jl#181]
Not sure if this is something to focus on here, or in JuMP; but it seems like the latest version bump has dependencies set up a bit odd.

I just ran `update` on one of my projects an got this:

> Updating `~/repos/project/Project.toml`
>    [b6b21f68] ↑ Ipopt v0.5.4 ⇒ v0.6.0
>    [4076af6c] ↓ JuMP **v0.19.2 ⇒ v0.18.6**
>   Updating `~/repos/project/Manifest.toml`
>   [6e4b80f9] + BenchmarkTools v0.4.2
>   [b6b21f68] ↑ Ipopt v0.5.4 ⇒ v0.6.0
>   [682c06a0] + JSON v0.21.0
>   [4076af6c] ↓ JuMP **v0.19.2 ⇒ v0.18.6**
>   [b8f27783] ↑ MathOptInterface v0.8.4 ⇒ v0.9.0
>   [69de0a69] + Parsers v0.3.6
>   [89212889] + ReverseDiffSparse v0.8.6

Doesn't seem like the plan would be revert to JuMP 0.18.6 at this point in time right?

**Comment by blegat** [comment]
See https://discourse.julialang.org/t/pkg-update-downgrade-jump/27621/4 and the discussion on the `jump-dev` channel of the slack.
For Pkg, it can either
* use the latest version of JuMP, MOI v0.8 and the version of Ipopt for MOI v0.8 or
* use JuMP v0.18, MOI v0.9 and the latest version of Ipopt.

The choice done by Pkg between these two Pareto optimal version choices is implementation defined (i.e. arbitrary).

**Comment by Libbum** [comment]
Got it. Thanks!

**Comment by odow** [comment]
Like https://github.com/JuliaOpt/Gurobi.jl/issues/232, let's leave this open until JuMP 0.20 is released, because others will undoubtedly have the same issue.

**Comment by mlubin** [comment]
JuMP 0.20 is released
