### ISSUE TITLE
How to install Ipopt v0.2.6 in Juliapro v0.5.2.3/julia v"0.5.2"??

### ISSUE THREAD

**Issue by Paindora77** [JuliaOpt/Ipopt.jl#186]
I want to run a code that need JuMPChance.jl and Ipopt.jl, this code developed in Julia v0.5. By using “”Pkg.clone()“”, I  successfullly installed  JuMPChance.jl . However, I tried a lot of ways to install ipopt.jl on julia v0.5,  but it didn't work. Please help me install Ipopt.jl v0.2.6 ,thank you. :-)

**Comment by blegat** [comment]
I would recommend updating to Julia v1.0 and JuMP v0.18, I have updated JuMPChance to these versions in https://github.com/mlubin/JuMPChance.jl/pull/20

**Comment by mlubin** [comment]
@Paindora77 Could you provide a more precise description of what didn't work? Using Julia 0.5 is not going to be a smooth experience anymore. If possible, as @blegat mentioned, it's advisable to use 0.6, 0.7, or 1.0.

**Comment by Paindora77** [comment]
Thank you!! It work !! :-)

**Comment by mlubin** [comment]
We'll consider this as resolved then :)
