### ISSUE TITLE
Ipopt problem scaling not working

### ISSUE THREAD

**Issue by kersulis** [JuliaOpt/Ipopt.jl#32]
I built a JuMP model with the following norm maximization objective:
```julia
setObjective(m,:Max,sum([(Qtheta[i,i]*z[i]^2) for i in 1:size(Qtheta,1)]))
```
When I use `MosekSolver()`, I get an error:
```text
MOSEK error 1296: The quadratic coefficient matrix in the objective is not negative semidefinite as expected for a maximization problem.
```
But when I use `IpoptSolver()`, it performs _minimization_ and says it has found an optimal solution. Here is some of the output:
```text
This is Ipopt version 3.11.7, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:     1032
Number of nonzeros in inequality constraint Jacobian.:       54
Number of nonzeros in Lagrangian Hessian.............:      279

Total number of variables............................:      279
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:      225
Total number of inequality constraints...............:       54
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:       54
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 -2.6589219e-04 2.14e+00 1.97e-02   0.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1 -7.7987052e-06 1.24e-14 2.45e-07 -11.0 3.41e+01    -  9.90e-01 1.00e+00h  1
   2 -7.7988784e-06 1.42e-14 2.46e-09 -11.0 2.57e-06    -  9.90e-01 1.00e+00h  1
   3 -7.8157914e-06 1.42e-14 1.43e-10 -11.0 2.50e-04    -  9.95e-01 1.00e+00h  1
   4 -8.3505974e-06 2.13e-14 8.63e-08  -8.8 4.52e-02    -  8.87e-01 9.96e-01h  1
   5 -9.5318281e-06 1.42e-14 4.61e-07  -8.4 1.05e+00    -  7.93e-01 6.17e-01f  1
   6 -9.9182203e-06 1.24e-14 1.42e-08  -9.2 2.69e-01    -  8.27e-01 9.59e-01f  1
   7 -9.9602587e-06 1.18e-14 2.00e-09 -10.3 3.04e-02    -  9.62e-01 1.00e+00h  1

Number of Iterations....: 7
```
I noticed [here](https://github.com/JuliaOpt/Ipopt.jl/blob/master/src/Ipopt.jl#L254) that Ipopt problem scaling may not work. Perhaps Ipopt is not switching from minimization to maximization when JuMP tells it to?

**Comment by tkelman** [comment]
Not sure whether JuMP actually uses that objective scaling function. More likely it's flipping the sign before it sends anything to the solver. At least that's what it looks like from testing on `JuMP/test/hockschittkowski/hs109.jl` and changing the objective sense. Can you post the whole code? If not, does `:Min, -sum` work?

**Comment by kersulis** [comment]
I tried `:Min` with negative objective, testing with Mosek and Ipopt. Mosek gave the same error as before (expected), and Ipopt gave the same values as when I used `:Max` with the original objective. I think everything is alright after all.

My apologies for the false alarm. Thank you for your help and for all the work you do!

**Comment by mlubin** [comment]
For nonconvex minimization problems, I believe the theory says that you can converge to stationary points which are not minimizers (i.e., you could converge to a local maximum).

**Comment by kersulis** [comment]
Good point. What I'm doing may be viewed as norm maximization with linear equality and inequality constraints. Because sets {x: x'x >= k} are nonconvex, I think I immediately lose global optimality guarantees right there. I've read that there are cases in which this problem is strongly dual however. I need to study further. Ever learning...
