### ISSUE TITLE
Error failed to find fortran compiler

### ISSUE THREAD

**Issue by rajhanschinmay** [JuliaOpt/Ipopt.jl#39]
When I am compiling IPOPT using msys and Mingw in Windows, it is saying,
failed to find a fortran compiler.
Checking for gfortran, ifort, g95, g77, f132, compile_f2c: all the answers are no.
I have installed fortran compiler using mingw.
Kindly let me know what can be wrong.

**Comment by tkelman** [comment]
Wherever you got mingw from, you need to install gfortran. This is the issue tracker for the *Julia* interface to Ipopt, not Ipopt itself. Please send questions like this that are completely unrelated to the Julia package to the Ipopt mailing list.
