### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by mes9** [JuliaOpt/Ipopt.jl#42]
Running Julia .3 in Windows 8.1
I cannot get Ipopt.jl to build. It returns the following:

INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1/repodata/repomd.xml
INFO: Building Ipopt
INFO: Nothing to do
================================[ ERROR: Ipopt ]================================

Provider PackageManager failed to satisfy dependency libipopt
while loading C:\Users\ms\.julia\v0.3\Ipopt\deps\build.jl, in expression starting on line 72

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Ipopt had build errors.

 - packages with build errors remain installed in C:\Users\Michael\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("Ipopt")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by tkelman** [comment]
Exactly which version are you using? What's the output of `versioninfo()`? How long ago did you first try to install the `Ipopt` package, and did you upgrade Julia versions recently?

**Comment by mes9** [comment]
I think my version of Julia might be too old. I'll try to update it and see if it fixes it. There is no command in Julia to update the version, correct?


Julia Version 0.3.4
Commit 3392026* (2014-12-26 10:42 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tkelman** [comment]
No, just download a new copy and install it separately. Using 0.3.10 or newer should fix this I believe.

**Comment by mes9** [comment]
It works! Thank you!! I appreciate your quick response
