### ISSUE TITLE
Ipopt broken on JuliaBox?

### ISSUE THREAD

**Issue by yanchiwei** [JuliaOpt/Ipopt.jl#50]
Hi, 
    I'm using Ipopt package on Julia 0.4.2 on Juliabox. It seems that it always return the following error message. However the same setting on my local computer runs just fine. It's the same version of the Ipopt package (0.2.0). Thanks in advance for the help!

   Exception of type: OPTION_INVALID in file "IpAlgBuilder.cpp" at line 321:
   Exception message: Selected linear solver MA27 not available.
   Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
    libhsl.so: cannot open shared object file: No such file or directory

Chiwei

**Comment by tkelman** [comment]
HSL is not freely downloadable or redistributable. You'll have to use mumps (the default, so removing the linear solver option setting should also work) on juliabox.

**Comment by tkelman** [comment]
@yanchiwei sorry I didn't understand the implications of what was happening here and test it for myself until a few days after seeing this. Ref https://github.com/JuliaLang/JuliaBox/issues/357, this should be fixed now. There was a misconfiguration in the way Ipopt had been compiled on JuliaBox, where it failed to download the default Mumps solver so built a non-functional library without any linear solver.

**Comment by yanchiwei** [comment]
Thank you Tony. It works!

Chiwei
