### ISSUE TITLE
Segmentation fault when installing Ipopt.jl on OSX

### ISSUE THREAD

**Issue by bstellato** [JuliaOpt/Ipopt.jl#53]
Hi there,

I am trying to install Ipopt on OSX 10.11.3 but I get a segmentation fault. I have Julia installed via Homebrew but the same happens if I use the .dmg package.

My Julia version is the following

```
Julia Version 0.4.3
Commit a2f713d* (2016-01-12 21:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.2.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

This is the output I get from a clean Julia installation without any other packages installed. 

```
julia> Pkg.add("Ipopt")
INFO: Installing BinDeps v0.3.21
INFO: Installing Compat v0.7.12
INFO: Installing Homebrew v0.2.0
INFO: Installing Ipopt v0.2.1
INFO: Installing JSON v0.5.0
INFO: Installing MathProgBase v0.4.2
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.2
INFO: Building Homebrew
INFO: Recompiling stale cache file /Users/sidereus/.julia/lib/v0.4/Compat.ji for module Compat.
INFO: Recompiling stale cache file /Users/sidereus/.julia/lib/v0.4/JSON.ji for module JSON.
INFO: Recompiling stale cache file /Users/sidereus/.julia/lib/v0.4/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file /Users/sidereus/.julia/lib/v0.4/URIParser.ji for module URIParser.
INFO: Recompiling stale cache file /Users/sidereus/.julia/lib/v0.4/SHA.ji for module SHA.
HEAD is now at c99e5c4 daemon: add 0.6.4 bottle.
HEAD is now at 4a13095 Merge pull request #85 from staticfloat/staging
INFO: Building Ipopt

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)

signal (11): Segmentation fault: 11
unknown function (ip: 0x31c1d1e25)
```

and it goes on forever. Do you have any idea of what could  cause the problem? I have seen that I get segmentation fault also when I run `Pkg.build("Ipopt")` or `BinDeps.debug("Ipopt")`.

**Comment by tkelman** [comment]
Can you try running in julia-debug and/or getting a backtrace in lldb or gdb?

**Comment by bstellato** [comment]
I ran `BinDeps.debug("Ipopt")` from julia-debug in lldb. This is the error:

```
(lldb) r
Process 2400 launched: '/usr/local/bin/julia-debug' (x86_64)
INFO: Reading build script...
The package declares 1 dependencies.
 - Library "libipopt"
    - Satisfied by:
      - System Paths at /usr/local/Cellar/ipopt/3.12.1_3/lib/libipopt.1.10.1.dylib
    - Providers:
      - Simple Build Process
      - Homebrew Bottles ipopt
signal (11): Segmentation fault: 11
unknown function (ip: 0x3114b7e25)
Process 2400 stopped
* thread #1: tid = 0x2993f, 0x00000003114b7e25, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3114b7e25)
    frame #0: 0x00000003114b7e25
error: memory read failed for 0x3114b7e00
```
The backtrace is here: [https://gist.github.com/bstellato/fd670b0e01ba0e320a82](url)

I have also Ipopt installed separately with Homebrew. It seems that the System Path library is linked to that installation. Could it be the problem?

**Comment by tkelman** [comment]
> I have also Ipopt installed separately with Homebrew. It seems that the System Paths refers to that installation. Could it be the problem?

Probably? Could you try uninstalling the homebrew-science version of Ipopt, re-running `Pkg.build("Ipopt")` and seeing if that makes a difference?

**Comment by bstellato** [comment]
Yes, apparently without the homebrew-science version the installation works. It seems that the ipopt binaries are not even downloaded when the homebrew-science version is present.

**Comment by tkelman** [comment]
Right, the default behavior in BinDeps is to try to use a pre-existing system version of the library if it's present and can be loaded (and passes any validation check hooks, if the package author has written any). The segfault really shouldn't be happening though. Does it happen if you try to call `Libdl.dlopen` on the homebrew-science libipopt.dylib? Who has a mac and can try to reproduce, @joehuchette? @iainnz? @yeesian?

**Comment by tkelman** [comment]
also @dpo from the homebrew-science side

**Comment by bstellato** [comment]
Nothing strange happens if I run `Libdl.dlopen`

```
julia> Libdl.dlopen("/usr/local/Cellar/ipopt/3.12.1_3/lib/libipopt.1.10.1.dylib")
Ptr{Void} @0x00007fedb5269910
```

**Comment by tkelman** [comment]
Okay, we may need to check exactly what `BinDeps.debug("ipopt")` is running then. There may have been some upstream change in Homebrew that might be causing issues in Homebrew.jl.

**Comment by dpo** [comment]
Does `brew test ipopt` work?

**Comment by bstellato** [comment]
I think it was a problem with homebrew-science ipopt. I recompiled it and the problem doesn't appear anymore when I try to install Ipopt.jl. I didn't run `brew test ipopt` before, so I am not sure whether it would have worked. Now it doesn't give any problems.
