### ISSUE TITLE
Error on IPOPT building

### ISSUE THREAD

**Issue by juantorres91** [JuliaOpt/Ipopt.jl#57]
Hi,

I'm trying to use the DSPsolver in Julia, for that reason I needed to get Ipopt but I'm having problems building the Package. I think i've got all the requirements because I built my own Ipopt version. I'm getting the following error in the building:
***************************************************************************************
libtool: link: `libipoptamplinterface.la' is not a valid libtool archive
make[3]: *** [ipopt] Error 1
make[3]: Leaving directory `/home/juan/.julia/v0.5/Ipopt/deps/src/Ipopt-3.12.1/Ipopt/src/Apps/AmplSolver'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/juan/.julia/v0.5/Ipopt/deps/src/Ipopt-3.12.1/Ipopt/src/Apps'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/juan/.julia/v0.5/Ipopt/deps/src/Ipopt-3.12.1/Ipopt'
make: *** [all-recursive] Error 1
================================================================[ ERROR: Ipopt ]=======================

Sincerely,

Juan

**Comment by tkelman** [comment]
What operating system are you using? Please provide as much information as you can.
