### ISSUE TITLE
Build of Ipopt fails with Julia 0.4.6 and 0.6 on Linux openSUSE

### ISSUE THREAD

**Issue by colbec** [JuliaOpt/Ipopt.jl#62]
Using:
```
julia> versioninfo()
Julia Version 0.6.0-dev.403
Commit f58aaef* (2016-08-25 07:12 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

```
JuMP and AmplNLWriter install OK but then system calls for CoinOptServices and during build process Ipopt has a problem. Part of error output on retry build of Ipopt:
```
configure: Using libtool script in directory ../..
checking if library version is set... 6:2:5
checking for pkg-config... pkg-config
checking pkg-config is at least version 0.16.0... yes
checking whether user supplied BLASLIB="/home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinblas.a -lgfortran" works... no
configure: error: user supplied BLAS library "/home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinblas.a -lgfortran" does not work
configure: error: /bin/sh './configure' failed for ThirdParty/Mumps
=========================================[ ERROR: Ipopt ]==========================================

LoadError: failed process: Process(`./configure --prefix=/home/colin/.julia/v0.6/Ipopt/deps/usr coin_skip_warn_cxxflags=yes '--with-blas=/home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinblas.a -lgfortran' --with-lapack=/home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinlapack.a ''`, ProcessExited(1)) [1]
while loading /home/colin/.julia/v0.6/Ipopt/deps/build.jl, in expression starting on line 81

===================================================================================================

=========================================[ BUILD ERRORS ]==========================================

WARNING: Ipopt had build errors.

 - packages with build errors remain installed in /home/colin/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Ipopt")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================


```

**Comment by tkelman** [comment]
Great, thanks. So the reason Ipopt rebuilds (the reference) blas is that it needs 32 bit integers, and it actually only uses a fairly small part of blas - libcoinblas only has real double-precision functions in it IIRC.

Can you gist the file at `/home/colin/.julia/v0.6/Ipopt/deps/src/Ipopt-3.12.1/ThirdParty/Mumps/config.log` ? That will contain a more detailed error output.

**Comment by tkelman** [comment]
Also what is `ls -al /home/colin/.julia/v0.6/Ipopt/deps/usr/lib/` and `ls -al /home/colin/.julia/v0.6/Ipopt/deps/usr/` ?

**Comment by colbec** [comment]
Gist here:
mumps config: https://gist.github.com/colbec/50b0e7b64628bfb463053dfea4db4f5c

Requested usr/lib does not exist, directory usr/lib64 exists:

```
> ls -al /home/colin/.julia/v0.6/Ipopt/deps/usr/ 
total 0
drwxr-xr-x 3 colin users  19 Aug 25 05:19 .
drwxr-xr-x 5 colin users  61 Aug 25 05:19 ..
drwxr-xr-x 3 colin users 113 Aug 25 05:21 lib64

> ls -al /home/colin/.julia/v0.6/Ipopt/deps/usr/lib64/
total 1216
drwxr-xr-x 3 colin users    113 Aug 25 05:21 .
drwxr-xr-x 3 colin users     19 Aug 25 05:19 ..
-rw-r--r-- 1 colin users 253774 Aug 25 05:21 libcoinblas.a
-rwxr-xr-x 1 colin users    782 Aug 25 05:21 libcoinblas.la
-rw-r--r-- 1 colin users 979298 Aug 25 05:21 libcoinlapack.a
-rwxr-xr-x 1 colin users    795 Aug 25 05:21 libcoinlapack.la
drwxr-xr-x 2 colin users     46 Aug 25 05:21 pkgconfig
```

**Comment by tkelman** [comment]
Yep, that explains it. It's the opensuse environment variable that tells autoconf/automake to build into `lib64`. Let me find where the Julia makefiles unset it, so we can try that here.

Not really needed this time, but just to share. The trick to reading `config.log` files when something goes wrong in a configure script is to search for the `## Cache variables. ##` section and look right above that. In this case it said:
```
configure:21960: checking whether user supplied BLASLIB="/home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinblas.a -lgfortran" works
configure:22077: gcc -o conftest -O3 -pipe -DNDEBUG    -DMUMPS_BUILD   conftest.c /home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinblas.a -lgfortran  >&5
gcc: error: /home/colin/.julia/v0.6/Ipopt/deps/usr/lib/libcoinblas.a: No such file or directory
```

...

Okay, found it. The environment variable is `CONFIG_SITE`. First, what is the value of `ENV["CONFIG_SITE"]` for you? Second, try
```
withenv(filter(x->x[1]!="CONFIG_SITE", collect(ENV))...) do
    Pkg.build("Ipopt")
end
```
You may need to `rm(Pkg.dir("Ipopt","deps","usr"); recursive=true)` first.

**Comment by colbec** [comment]
```
> echo $CONFIG_SITE
/usr/share/site/x86_64-unknown-linux-gnu
```

Suggestion to rm(...) followed by withenv(...) resulted in same error as above.

FWIW, as an ugly hack I made a symbolic link from new usr/lib to usr/lib64 and the build works correctly.

**Comment by tkelman** [comment]
Oh that's how that works, `/usr/share/site/x86_64-unknown-linux-gnu` is a file that will have a bunch of content in it. Worth gisting maybe?

I made an edit and you might need to also `rm(Pkg.dir("Ipopt","deps","src"); recursive=true)` - the first time when you still got the error, how much of building the library did it re-do? It might have started from cached content in src, I'm not sure.

**Comment by tkelman** [comment]
Or since I might be mistaken with what `withenv` will do for unset-ing certain environment variables, just
```julia
pop!(ENV, "CONFIG_SITE")
Pkg.build("Ipopt")
```
remembering to re-set it if you'd like (or just restart Julia to get it back to the default).

**Comment by colbec** [comment]
x86_64-unknown-linux-gnu is actually a bash script which is invoked. Here is the gist:
https://gist.github.com/colbec/681dd307d48d73bc6033d1f8640c19ed
I just completed an optimization problem to check that all was in place and it worked well. Now I will try the steps you suggest.

**Comment by tkelman** [comment]
I think #63 should fix this - if your manual tests with `pop!(ENV, "CONFIG_SITE")` work, would you mind clearing out the `deps/src` and `deps/usr` again and do
```julia
Pkg.checkout("Ipopt")
Pkg.checkout("Ipopt", "tk/fix62")
ENV["MAKEFLAGS"] = "-j4" # save some time
Pkg.build("Ipopt")
Pkg.test("Ipopt")
# and eventually go back to release once a new version of the package gets tagged
Pkg.free("Ipopt")
```

**Comment by colbec** [comment]
Just finished the  `pop!(ENV, "CONFIG_SITE")` exercise and it worked. Previously had tried removing src and usr followed by `Pkg.update()` but that step failed. Now running latest.

**Comment by colbec** [comment]
@tkelman As a result of the new setup I am now no longer able to load AmplNLWriter which had worked before. I have tried to rebuild AmplNLWriter and restarted Julia according to standard instructions but no load.  Is this related to this issue or should I be cleaning out my cache perhaps?

```
ERROR: LoadError: LoadError: LoadError: Unable to load 

libOS (/home/colin/.julia/v0.6/CoinOptServices/deps/usr/lib64/libOS.so)

Please re-run Pkg.build(package), and restart Julia.
 in include_from_node1(::String) at ./loading.jl:481 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:409
 in include_from_node1(::String) at ./loading.jl:481
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:409
while loading /home/colin/.julia/v0.6/CoinOptServices/src/../deps/deps.jl, in expression starting on line 12
while loading /home/colin/.julia/v0.6/CoinOptServices/src/CoinOptServices.jl, in expression starting on line 20
while loading /home/colin/.julia/v0.6/AmplNLWriter/src/AmplNLWriter.jl, in expression starting on line 28
```

**Comment by tkelman** [comment]
Hm, interesting. It's possible that CoinOptServices needs the same change as #63, or maybe you'd need to delete `deps/usr` and `deps/src` from CoinOptServices as well. Apologies about all the recompilation you're doing, I appreciate the willingness to test. I feel like I would have tested these things when I was booting into my OpenSUSE partition more regularly, but now I can't remember for sure.

**Comment by colbec** [comment]
Just confirming that delete of src and usr for CoinOptServices followed by Pkg.build() fixed the load problem. Back to working status. Thank you for your help and not a problem doing testing, it's my contribution to the effort.

**Comment by tkelman** [comment]
Great! Just to confirm, by "Now running latest" you mean post-`Pkg.checkout("Ipopt", "tk/fix62")`, right? We'll get that merged and tagged soon then, once one of the other maintainers gets a chance to review it.

**Comment by colbec** [comment]
In Julia 0.6
```
julia> Pkg.status("Ipopt")
 - Ipopt                         0.2.4+             tk/fix62
```

**Comment by tkelman** [comment]
oh yeah i still need to tag this i think. let's see if #66 needs any changes to be made first
