### ISSUE TITLE
Lasso problem with Ipopt: how to pass the data to Ipopt for PDE-constrained optimization

### ISSUE THREAD

**Issue by chegini** [JuliaOpt/Ipopt.jl#64]
Hi, firstly, thank you so much for the Julia interface to the Ipopt nonlinear solver.

I am working on a PDE-constrained optimization problem, where I need to pass the data to the IPOPT solver, something similar to the in Matlab example e.g. the Lasso problem which uses Ipopt (see: http://www.cs.ubc.ca/~pcarbo/ipopt-for-matlab/lasso.m).

Do you have any equivalent example in Julia? if not, could you possibly provide and example where one passes this kind of data to the solver?

**Comment by tkelman** [comment]
Are you using the low-level interface? You can make a closure. If the function you want to write looks like `eval_f(x, data)` then just send `x -> eval_f(x, data)` as the function when you call `createProblem`. On Julia 0.5 that should be the same performance. On Julia 0.4 it might have a little bit of a performance penalty but for a large problem most of the time should be spent in the Ipopt linear algebra rather than function evaluations.

**Comment by chegini** [comment]
Thanks for reply. 
I am using  Julia interface 5.0 . As you said I made a closure as follows:

`function **testfunc**(x,data)
  function eval_f(x,data) 
    println(data)
    return x[1] * x[4] * (x[1] + x[2] + x[3]) + x[3]
  end
  return eval_f
end
.
.
.
global **data** = 10
prob = createProblem(n, x_L, x_U, m, g_L, g_U, 8, 10,
                     **testfunc**, eval_g, eval_grad_f, eval_jac_g, eval_h)  `
.
.
.
-------------------------------------------------------------------------------
data is defined as a global variable. Now I have this error:
-------------------------------------------------------------------------------
ERROR: LoadError: MethodError: no method matching testFunc(::Array{Float64,1})
Closest candidates are:
  testFunc(::Any, !Matched::Any) at /Users/fatimachegini/.julia/v0.5/Ipopt/example/hs071.jl:11
 in eval_f_wrapper(::Int32, ::Ptr{Float64}, ::Int32, ::Ptr{Float64}, ::Ptr{Void}) at /Users/fatimachegini/.julia/v0.5/Ipopt/src/Ipopt.jl:89
 in solveProblem(::Ipopt.IpoptProblem) at /Users/fatimachegini/.julia/v0.5/Ipopt/src/Ipopt.jl:304
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/fatimachegini/.julia/v0.5/Ipopt/example/hs071.jl, in expression starting on line 113
-------------------------------------------------------------------------------
Could you please tell what is wrong here?

**Comment by chegini** [comment]
Hi,
I defined the data as a global variable, now it works.
