### ISSUE TITLE
Ipopt + Julia: Can we solve a problem without constraints?

### ISSUE THREAD

**Issue by chegini** [JuliaOpt/Ipopt.jl#65]
Hi,
I already wrote a script  in **Matlab** to solve a PDE-constrained optimization problem by defining **the adjoint formulation** and I used Ipopt which works well. It means I don't define any constraints in Matlab version. But I have the following error when I don't define the constraints in **julia** :
**ERROR: LoadError: IPOPT: Failed to construct problem.**

 I even tried to solve a simple problem with **no-constraints**, I have again the same error. Could you please tell me if it is possible using Ipopt in Julia without Constraints? 

Thanks in advance

**Comment by tkelman** [comment]
Should be able to handle unconstrained problems. Can you post a complete code sample that reproduces the issue?

**Comment by chegini** [comment]
You are right, I just found the problem, I made a mistake for setting nele_jac.(Number of the element for jacobian), it was supposed to be zeros in this case. 👍 Thanks for quick response.
