### ISSUE TITLE
Ipopt Installation Julia 0.5 Mac

### ISSUE THREAD

**Issue by econotron** [JuliaOpt/Ipopt.jl#68]
The Ipopt.jl build is failing on macOS Sierra, 10.12, with Julia 0.5. It cannot find a Fortran compiler:

configure: WARNING: Failed to find a Fortran compiler!

despite me installing Fortran at

which gfortran
/usr/local/bin/gfortran

I got gfortran 6.2 binaries from

http://hpc.sourceforge.net

Thanks for looking into this, Jeremy

**Comment by mlubin** [comment]
CC @staticfloat

**Comment by chkwon** [comment]
```
julia> Pkg.build("Ipopt")
INFO: Building Homebrew
Updated 1 tap (homebrew/core).
No changes to formulae.
INFO: Building Ipopt
WARNING: The following packages do not have relocatable bottles, installation may fail!
Please report these packages to https://github.com/JuliaLang/Homebrew.jl:
  staticfloat/juliadeps/ipopt
==> Installing ipopt from staticfloat/juliadeps
==> Installing dependencies for staticfloat/juliadeps/ipopt: gcc, staticfloat/juliadeps/libgfortran
==> Installing staticfloat/juliadeps/ipopt dependency: gcc
==> Using the sandbox
==> Downloading https://ftpmirror.gnu.org/gcc/gcc-6.2.0/gcc-6.2.0.tar.bz2
Already downloaded: /Users/chkwon/Library/Caches/Homebrew.jl/gcc-6.2.0.tar.bz2

==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e9e0e
Already downloaded: /Users/chkwon/Library/Caches/Homebrew.jl/gcc--patch-863957f90a934ee8f89707980473769cff47ca0663c3906992da6afb242fb220.patch
==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> ../configure --build=x86_64-apple-darwin16.0.0 --prefix=/Users/chkwon/.julia
==> make bootstrap
```

In my case, it stops here, and the fan becomes crazy noisy.

**Comment by econotron** [comment]
It doesn’t really stop just takes an awful long time. It eventually got
past that step and ended with the Fortran error, on my machine.

**Comment by mlubin** [comment]
I'm guessing 10.12 just isn't supported yet.

**Comment by tkelman** [comment]
correct. don't upgrade right away if you want homebrew binaries from external taps to still be available https://github.com/JuliaPackaging/Homebrew.jl/issues/154

**Comment by tkelman** [comment]
homebrew annoyingly will build gcc from source without warning you first if you have xcode but not the command line tools installed. we should see if there's a flag to avoid that, it's happened to multiple people I know.

**Comment by staticfloat** [comment]
It does print out a warning, but yeah, that's really annoying.  That's new in 10.12 from what I understand; Xcode 8 doesn't ship `libgcc_s.dylib` without the CLT. 😮

**Comment by tkelman** [comment]
I was seeing that happen several weeks ago on colleague's systems, it's been happening before 1.12
