### ISSUE TITLE
Hessian handling doesn't fully adhere to MathProgBase interface?

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/Ipopt.jl#70]
First, thank you for making this interface available!

I did run into a small issue while working with Ipopt via the MathProgBase interface. The [MathProgBase documentation for `hesslag_structure`](https://mathprogbasejl.readthedocs.io/en/latest/nlp.html#hesslag_structure) says:

>
Returns the sparsity structure of the Hessian-of-the-Lagrangian matrix [...] as a tuple (I,J) where I contains the row indices and J contains the column indices of each structurally nonzero element. These indices are not required to be sorted and **can contain duplicates, in which case the solver should combine the corresponding elements by adding them together**. [...]

Could it be that Ipopt.jl currently doesn't handle the part I emphasized correctly? In the [Ipopt documentation for eval_h](http://www.coin-or.org/Ipopt/documentation/node23.html#SECTION00053180000000000000), I don't see any mention of Ipopt handling this requirement, and I don't see it in `eval_h_cb` either.

**Comment by tkoolen** [comment]
Knitro.jl's `eval_h_cb` callback for comparison: https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/KnitroSolverInterface.jl#L180.

**Comment by mlubin** [comment]
Ipopt definitely handles this correctly. JuMP takes full advantage of it.

http://www.coin-or.org/Ipopt/documentation/node38.html#app.triplet
"The individual elements of the matrix can be listed in any order, and if there are multiple items for the same nonzero position, the values provided for those positions are added."

**Comment by tkoolen** [comment]
Alright, my mistake, thank you; then I guess something else is wrong in my code.
