### ISSUE TITLE
ReadOnlyMemoryError(), Ipopt 0.2.6, Julia 0.5.1

### ISSUE THREAD

**Issue by xqrongm** [JuliaOpt/Ipopt.jl#81]
Julia v"0.5.1"
Ipopt 0.2.6
JuMP 0.16.1

Running the following code resulted in `ReadOnlyMemoryError()`
```
using Ipopt, JuMP

X = 1:10
Y = (2:11) + rand(10)/10

m = Model(solver=IpoptSolver(print_level=0, max_iter=35))

@variable(m, a)
@variable(m, b)

@objective(m, Min, sum((a* X[i] + b - Y[i]) ^ 2 for i in X))

status = solve(m)
```

It returns successfully on Julia v"0.5.0" and the same version of Ipopt. Using another solver on Julia v"0.5.1" also returns successfully.

**Comment by tkelman** [comment]
Did you install Ipopt some time ago? Try making a copy of .julia/WinRPM/deps/usr, move it out of the way and re-do Pkg.build()

**Comment by xqrongm** [comment]
Thanks for the suggestion. I did install Ipopt a while ago. Sorry I'm not an expert for Julia so I don't quite understand your instruction. Is this what I should do:

(My "JULIA_PKGDIR" is "E:\for_programs\julia_pkgs")
Copy "E:\for_programs\julia_pkgs\v0.5\WinRPM\deps\usr" to somewhere else like "E:\backup\usr"
In Julia REPL:
```
cd("E:/for_programs/julia_pkgs/v0.5/WinRPM/deps/usr")
Pkg.build()
```
which is re-building some WinRPM components? And it'll fix the issue with Ipopt?

What should I do with the backup copy at "E:\backup\usr"? Copy it back to "E:\for_programs\julia_pkgs\v0.5\WinRPM\deps\usr" in case `Pkg.build()` doesn't work?
Thanks!

**Comment by tkelman** [comment]
Right, though after making a backup copy, delete the original or move it out of the way.

**Comment by xqrongm** [comment]
Thanks. I tried the instruction but it resulted in build errors for multiple packages. I did 
```
# restart Julia after each line
Pkg.rm("WinRPM")
Pkg.add("WinRPM")
using WinRPM; WinRPM.update()
Pkg.build()
```
And finally seemed to get everything to work.
I understand these issues are normal for a language in heavy development. I hope they'll get fixed eventually. Thanks.

**Comment by mlubin** [comment]
Does this affect anyone who had a working install on 0.5.0 and upgraded to
0.5.1?

**Comment by tkelman** [comment]
probably

**Comment by jsschlosser** [comment]
I have tried several approaches to this solving this but for some reason, I keep getting the same error:

julia> Wipopt, Hipopt, pipopt = Mads.NMFipopt(X, nk, retries=1);
ERROR: UndefVarError: Ipopt not defined
 in #NMFipopt#240(::Int64, ::Float64, ::Bool, ::Int64, ::Int64, ::Array{Float64,2}, ::Array{Float64,2}, ::Int64, ::Bool, ::Mads.#NMFipopt, ::Array{Float64,2}, ::Int64) at C:\Users\Joseph\.julia\v0.5\Mads\src\..\src-new\MadsBSS.jl:47
 in (::Mads.#kw##NMFipopt)(::Array{Any,1}, ::Mads.#NMFipopt, ::Array{Float64,2}, ::Int64) at .\<missing>:0

I am using version 0.5.2 for Windows 10. Can anyone point me in the right direction?

**Comment by tkelman** [comment]
Not a bug in this package. Mads is doing unreliable things with conditional imports.

**Comment by jsschlosser** [comment]
Does it have anything to do with Windows vs. MAC? Any ideas on how to fix this issue?

**Comment by tkelman** [comment]
UndefVarError shouldn't be platform dependent. Report as a bug on the Mads.jl repo.
