### ISSUE TITLE
Initial values for the multipliers (warm start dual variables IPOPT)

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaOpt/Ipopt.jl#88]
How do supply we initial values of the constraint and bound multipliers to IPOPT for a true warm start ? 
I cant seem find any option to do so in the package documentation. Is there somewhere in the code, you can point me to where I can implement that ?

I am talking about the inputs mentioned in bullet =3, sub-bullet 2 [here](https://www.coin-or.org/Ipopt/documentation/node22.html)

thanks,
Nitin

**Comment by Wikunia** [comment]
Yeah that would be interesting. Did you find a solution?

**Comment by mlubin** [comment]
The multiplier vectors are passed [here](https://github.com/JuliaOpt/Ipopt.jl/blob/8cbdce598722270e7b8e5ae9d2628f8b82ba0833/src/Ipopt.jl#L304). We will not be exposing this functionality though MathProgBase. It will (eventually) be available in MathOptInterface.

**Comment by mlubin** [comment]
MPB is deprecated. https://github.com/JuliaOpt/Ipopt.jl/issues/164 tracks support for dual warm starts in the MOI wrapper.
