### ISSUE TITLE
Ipopt 3.12.8

### ISSUE THREAD

**Issue by arunveeramany** [JuliaOpt/Ipopt.jl#89]
Hi,

Is it possible to install Ipopt 3.12.8 when I do Pkg.add("Ipopt")?

Thanks

**Comment by timholy** [comment]
I successfully did this by changing the `dep/build.jl` script, removing the Ipopt directory from `deps/src`, and then saying `Pkg.build("Ipopt")`. See also #96.

**Comment by arunveeramany** [comment]
Thank you Tim.

So is it enough for me to Pkg.rm(“Ipopt”) and then again Pkg.add(“Ipopt”)?
I still see Ipopt v0.2.6

Thanks,

Arun

**Comment by timholy** [comment]
If you `Pkg.rm` followed by `Pkg.clone`, it should work. For `Pkg.add` you'd have to wait until a new release gets tagged.

Normally you might be able to do `Pkg.add` followed by `Pkg.checkout`. But in this case I'm not sure it would rebuild a new version unless you remove the file like I described above. So `Pkg.clone` seems safer.

**Comment by arunveeramany** [comment]
After a rm and clone, I see the following version reported. Is this 3.12.8?

- Ipopt                         0.2.6+             master


Thanks!

**Comment by arunveeramany** [comment]
Never mind, while running a script I see

******************************************************************************
This is Ipopt version 3.12.8, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).




From: Veeramany, Arun
Sent: Thursday, January 11, 2018 9:24 AM
To: 'JuliaOpt/Ipopt.jl'; JuliaOpt/Ipopt.jl
Cc: Author
Subject: RE: [JuliaOpt/Ipopt.jl] Ipopt 3.12.8 (#89)

After a rm and clone, I see the following version reported. Is this 3.12.8?

- Ipopt                         0.2.6+             master


Thanks!
