### ISSUE TITLE
MUMPS site down: `Pkg.build("Ipopt")` fails

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/Ipopt.jl#90]
It appears that http://mumps.enseeiht.fr/ is down, causing `Pkg.build("Ipopt")` to fail.

Just so that it's documented; I don't expect Ipopt.jl maintainers to be able to do anything about it.

**Comment by mlubin** [comment]
This is a pretty frequent issue. PR's accepted, probably would require patching Ipopt's makefiles.
