### ISSUE TITLE
Status: error [Restoration_Failed]

### ISSUE THREAD

**Issue by Wikunia** [JuliaOpt/Ipopt.jl#91]
I'm basically adding a constraint of the form `var <= constant` or `var >= constant` to the model.
(Branch and Bound)
and getting the status `:Error` or more specifically `Restoration_Failed`
Can someone give me a short explanation of what that means?

**Comment by mlubin** [comment]
https://list.coin-or.org/pipermail/ipopt/2007-May/000787.html
You should modify the variable upper or lower bounds instead of adding such constraints.

**Comment by Wikunia** [comment]
Oh yeah that's a nice tip. Forgot that stuff like this is possible and it's much cleaner. 
I just realized that the restoration error actually happens before the branch and bound (don't know why it didn't show me the warning then).

**Comment by juliohm** [comment]
@mlubin could you please elaborate on your comment? What you mean by modifying upper and lower bounds? Checked the documentation and can't find an alternative other than inequality constraints.

**Comment by Wikunia** [comment]
You can use: `JuMP.setlowerbound(x, 1.0)` to set the lower bound of the variable x to 1.0. 
This is documented here: http://www.juliaopt.org/JuMP.jl/0.18/probmod.html

**Comment by juliohm** [comment]
Thank you @Wikunia , what is the difference between setting the lowerbounds directly versus in the constraints? Is there a semantic difference?

**Comment by Wikunia** [comment]
They are used in a different manner by the solver. The simplex algorithm for example is different if you set the bounds instead of adding constraints.

**Comment by juliohm** [comment]
Thanks @Wikunia , I understand that box constraints are easier to handle. I am assuming the syntax you linked means that. I will give it a try to see if the error goes away.
