### ISSUE TITLE
Print Iteration Output

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaOpt/Ipopt.jl#93]
Hi,

I modified the JuMP [MLE example](https://github.com/JuliaOpt/JuMP.jl/blob/release-0.18/examples/mle.jl) to print every iteration's output:

`using JuMP, Ipopt

n = 1000
data = randn(n)

m = Model(solver=IpoptSolver(print_level=0, print_frequency_iter=1))

@variable(m, μ, start = 0.0)
@variable(m, σ >= 0.0, start = 1.0)

@NLobjective(m, Max, (n/2)*log(1/(2π*σ^2))-sum((data[i]-μ)^2 for i=1:n)/(2σ^2))

@NLconstraint(m, μ == σ^2)

solve(m)`

But nothing is printed. I ran this code with Jupyter, Julia 0.6, Ipopt 0.2.6.

**Comment by odow** [comment]
You have `print_level=0`, which will suppress all output. [Here](https://www.coin-or.org/Ipopt/documentation/node41.html) is the list of display options.

btw: you can display multi-line segments of code using triple back-ticks (i.e ` ``` `), rather than the single back-tick as you have used above.
