### ISSUE TITLE
Pkg.build("Ipopt") failing on mac OS High Sierra

### ISSUE THREAD

**Issue by MFairley** [JuliaOpt/Ipopt.jl#94]
Ipopt is currently failing to build on mac OS High Sierra due to https://github.com/staticfloat/homebrew-juliadeps/issues/120

**Comment by mlubin** [comment]
Time to investigate getting Ipopt from Conda via Conda.jl? https://anaconda.org/conda-forge/ipopt

**Comment by tkelman** [comment]
Requiring an entire miniconda distribution is way overkill for a handful of dylibs...

**Comment by mlubin** [comment]
If that covers OS X and windows for the most of the solvers under JuliaOpt, doesn't seem too unreasonable. Nobody's jumping up and down to maintain the current binaries.

**Comment by tkelman** [comment]
It doesn't cover Windows in a way that's actually usable here.

**Comment by mlubin** [comment]
Why aren't the conda binaries useful on windows? I haven't looked into it yet.

**Comment by tkelman** [comment]
It's just a repackaging of the same binaries that were used here before 2015. No ampl executable, not threadsafe, wrong compiler.

**Comment by mlubin** [comment]
Good to know, thanks. We're also talking about windows binaries using Conda for SCS at https://github.com/JuliaOpt/SCS.jl/pull/85.

**Comment by schalil** [comment]
I am trying to install Ipopt on Mac
~~~~~
julia> Pkg.build("Ipopt")
INFO: Building Homebrew
Updated 1 tap (homebrew/core).
No changes to formulae.
INFO: Building Ipopt
WARNING: The following packages do not have relocatable bottles, installation may fail!
Please report these packages to https://github.com/JuliaLang/Homebrew.jl:
  staticfloat/juliadeps/libgfortran
  staticfloat/juliadeps/ipopt
~~~~~

~~~
====================================================================[ ERROR: Ipopt ]====================================================================

LoadError: failed process: Process(`/Users/sreenathmadathil/.julia/v0.6/Homebrew/deps/usr/bin/brew install --ignore-dependencies staticfloat/juliadeps/libgfortran`, ProcessExited(1)) [1]
while loading /Users/sreenathmadathil/.julia/v0.6/Ipopt/deps/build.jl, in expression starting on line 89

========================================================================================================================================================

====================================================================[ BUILD ERRORS ]====================================================================

WARNING: Ipopt had build errors.

 - packages with build errors remain installed in /Users/sreenathmadathil/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Ipopt")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================================================

~~~

**Comment by tristanls** [comment]
I'm not sure how this is supposed to work on a Mac?

```
...
==> cd ThirdParty/Mumps; ./get.Mumps
==> ./configure --with-blas=/Applications/JuliaPro-0.6.1.1.app/Contents/Resources/pkgs-0.6.1.1/v0.6/Homebrew/deps/usr/Cellar/ipopt/3.12.4_1/lib/libcoinblas.a --with-lapack=/Applications/JuliaPro-0.6.1
==> make
Last 15 lines from /Users/tristan/Library/Logs/Homebrew/ipopt/08.make:
2018-01-01 14:05:03 -0600

make

Making all in ThirdParty/ASL
./compile_MS_ASL
./compile_MS_ASL: line 56: nmake: command not found
```

**Comment by mlubin** [comment]
I'm inferring from lack of activity at https://github.com/staticfloat/homebrew-juliadeps/issues/120 that the Julia homebrew binaries are no longer being actively maintained. Whoever needs this working automatically should look into https://github.com/JuliaPackaging/BinaryBuilder.jl.

**Comment by chkwon** [comment]
@mlubin Can Ipopt.jl take advantage of https://github.com/Homebrew/homebrew-science/blob/f238dec2f6a4210c0594b1900d7645dd3036f3ce/ipopt.rb?

**Comment by tkelman** [comment]
homebrew-science has occasionally provided binaries ("bottles") of ipopt, but not all of the time. homebrew-science was also recently completely deprecated by the homebrew project and is no longer supported. Many, but not all, commonly used homebrew-science packages were migrated into homebrew-core. Ipopt was not among those - https://github.com/Homebrew/homebrew-science/issues/6331

**Comment by mpf** [comment]
[This thread](https://github.com/staticfloat/homebrew-juliadeps/issues/120) seems to indicate that the workaround is to install Ipopt via Homebrew. but the corresponding homebrew-science formula has been deprecated.

Until this is resolved, what is the best workaround for installing Ipopt.jl?

**Comment by tkelman** [comment]
Your best bet may be collaborating with the people who were working on https://github.com/Homebrew/homebrew-core/pull/22368 and other linked PR's therein to work towards getting an ipopt formula into mainline Homebrew. It might meet Homebrew's notability requirement. Ipopt was the 15th most downloaded formula in homebrew-science last summer according to https://github.com/Homebrew/homebrew-core/issues/15619#issuecomment-321854868

**Comment by mlubin** [comment]
@staticfloat mentioned that Ipopt will be used as one of the example packages to test out BinaryBuilder. Any update on the timeline?

**Comment by ccoffrin** [comment]
For anyone following this thread, a quick fix for me was to add `.julia/v0.6/Homebrew/deps/usr/lib` to my `DYLD_LIBRARY_PATH`.

**Comment by mopg** [comment]
@ccoffrin do you just add that to your `.bash_profile`? Because I still keep getting those same errors.

**Comment by ccoffrin** [comment]
Some how my install managed to pull down ipopt's dylib into that directory.  If you don't see it there then I would not expect this quick fix to work.

**Comment by jac0320** [comment]
@ccoffrin Was that because you had Ipopt installed before? If the installation fresh, ipopt's dylib wouldn't be there until it gets compiled?

**Comment by ccoffrin** [comment]
I am not quite sure how it got there, but if you have ipopt's dylib any place in your system make sure to add its directory to `DYLD_LIBRARY_PATH`.

**Comment by chkwon** [comment]
`homebrew-science` is archived at [brewsci/homebrew-science](https://github.com/brewsci/homebrew-science).

Perhaps one can do:
`brew install brewsci/science/ipopt`
then
`Pkg.build("Ipopt")`

It just takes forever to compile.

**Comment by chkwon** [comment]
If you want a binary file for high sierra, you may try:

`brew install chkwon/juliaopt/ipopt`
then
`Pkg.build("Ipopt")`

This is the binary file that I compiled and bottled in my mac with a slight modification from @staticfloat's [recipe](https://github.com/staticfloat/homebrew-juliadeps/blob/master/ipopt.rb).

Hope this binary file distribution does not violate any license.

**Comment by jac0320** [comment]
Or, as a quick path before this issue is resolved for high sierra users, one can simply build Ipopt independently using (https://github.com/coin-or/Ipopt) and include the .dylib into `DYLD_LIBRARY_PATH`. The following works for me as a temp solution.

```
git clone https://github.com/coin-or/Ipopt
cd Ipopt
git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
BuildTools/get.dependencies.sh fetch
mkdir build
cd build
../configure
make install
```
And simple include `$(where you git clone ipopt)/Ipopt/build/lib` into `DYLD_LIBRARY_PATH`. Go to Julia and `Pkg.build("Ipopt")`.

**Comment by mopg** [comment]
@jac0320 Awesome, that worked for me! Thanks.

**Comment by floswald** [comment]
another solution completely within julia [here](https://github.com/staticfloat/homebrew-juliadeps/issues/120#issuecomment-362394464) within issue https://github.com/staticfloat/homebrew-juliadeps/issues/120

no manual linking required.

**Comment by mlubin** [comment]
This should be fixed now on `master`. I'll tag a release soon.

**Comment by mlubin** [comment]
Now released. Please report any issues that arise with the new binaries.

**Comment by chkwon** [comment]
Works perfect in macOS High Sierra.
