### ISSUE TITLE
Problem causes WARNING: Search_Direction_Becomes_Too_Small

### ISSUE THREAD

**Issue by MFairley** [JuliaOpt/Ipopt.jl#95]
I am getting these warnings when trying to solve the particular problem below. I have copied code here that can reproduce the error.

WARNING: Ipopt finished with status Search_Direction_Becomes_Too_Small
WARNING: Not solved to optimality, status: Error

```
using JuMP
using Ipopt

function test_ipopt()
    model = Model(solver = IpoptSolver())
    # model = Model(solver=MosekSolver())
    
    @variable(model, 0 <= x <= 1)
    @variable(model, s[1:10] >= 0)
    @NLobjective(model, Max, 35.95051084102152 * x + 0.1 * sum(log(v) for v in s))
    
    @constraint(model, x + s[1] == 0.0034580308011081798)
    @constraint(model, x + s[2] == 25.005338828298388)
    @constraint(model, x + s[3] == 38.00318553314289)
    @constraint(model, x + s[4] == 3.0056111951265856)
    @constraint(model, x + s[5] == 31.005338828298388)
    @constraint(model, x + s[6] == 21.005611195126587)
    @constraint(model, x + s[7] == 25.00533869746837)
    @constraint(model, x + s[8] == 12.00533869746837)
    @constraint(model, x + s[9] == 28.002880666667263)
    @constraint(model, x + s[10] == 0.002880535837244679)
    
    status = solve(model)
    
    println(model)
    println("status = $status")
    println("x = $(getvalue(x))")
    println("s = $(getvalue(s))")
    println("objective = $(getobjectivevalue(model))")

end
```

julia> test_ipopt()
This is Ipopt version 3.12.8, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:       20
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:       10

Total number of variables............................:       11
                     variables with only lower bounds:       10
                variables with lower and upper bounds:        1
                     variables with only upper bounds:        0
Total number of equality constraints.................:       10
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  4.2456664e+00 3.80e+01 6.73e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  4.7779567e+00 3.80e+01 9.87e+02  -1.0 1.99e+01    -  5.00e-04 5.46e-04h  1
   2  3.2066772e+00 3.76e+01 1.00e+05  -1.0 3.80e+01    -  5.48e-04 9.35e-03f  1
   3  4.7406057e+00 3.39e+01 4.72e+20  -1.0 3.76e+01    -  1.31e-02 9.90e-02f  1
   4  3.2163594e+00 3.55e-15 2.36e+20  -1.0 3.39e+01    -  9.65e-01 1.00e+00f  1
   5  3.1470447e+00 0.00e+00 1.18e+20  -1.0 3.55e-15    -  1.00e+00 1.00e+00   0
   6  3.0777299e+00 0.00e+00 5.90e+19  -1.0 8.47e-22    -  1.00e+00 1.00e+00   0
   7  3.0084152e+00 0.00e+00 2.95e+19  -1.0 1.69e-21    -  1.00e+00 1.00e+00T  0
   8  2.9391005e+00 0.00e+00 1.48e+19  -1.7 3.39e-21    -  1.00e+00 1.00e+00T  0
   9  2.8697858e+00 0.00e+00 7.38e+18  -2.5 6.78e-21    -  1.00e+00 1.00e+00   0
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  2.8004711e+00 0.00e+00 3.69e+18  -2.5 1.36e-20    -  1.00e+00 1.00e+00   0
  11  2.7311564e+00 0.00e+00 1.84e+18  -2.5 2.71e-20    -  1.00e+00 1.00e+00T  0
  12  2.6618416e+00 0.00e+00 9.22e+17  -3.8 5.42e-20    -  1.00e+00 1.00e+00T  0
  13  2.5925269e+00 4.34e-19 4.61e+17  -5.7 1.08e-19    -  1.00e+00 1.00e+00   0
  14  2.5232122e+00 4.34e-19 2.31e+17  -5.7 6.51e-19    -  1.00e+00 1.00e+00   0
  15  2.4538975e+00 0.00e+00 1.15e+17  -5.7 4.34e-19    -  1.00e+00 1.00e+00T  0
  16  2.3845828e+00 0.00e+00 5.76e+16  -8.6 8.67e-19    -  1.00e+00 1.00e+00T  0
  17  2.3152680e+00 0.00e+00 2.88e+16  -9.0 1.73e-18    -  1.00e+00 1.00e+00T  0

Number of Iterations....: 17

                                   (scaled)                 (unscaled)
Objective...............:   2.3152680429391075e+00    2.3152680429391075e+00
Dual infeasibility......:   2.8823037615163624e+16    2.8823037615163624e+16
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   9.0909090909090993e-10    9.0909090909090993e-10
Overall NLP error.......:   2.8823037615163624e+16    2.8823037615163624e+16

Number of objective function evaluations             = 18
Number of objective gradient evaluations             = 18
Number of equality constraint evaluations            = 18
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 18
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 18
Total CPU secs in IPOPT (w/o function evaluations)   =      0.006
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Search Direction is becoming Too Small.
WARNING: Ipopt finished with status Search_Direction_Becomes_Too_Small
WARNING: Not solved to optimality, status: Error
Max 35.95051084102152 * x + 0.1 * (log(s[1]) + log(s[2]) + log(s[3]) + log(s[4]) + log(s[5]) + log(s[6]) + log(s[7]) + log(s[8]) + log(s[9]) + log(s[10]))
Subject to
 x + s[1] = 0.0034580308011081798
 x + s[2] = 25.005338828298388
 x + s[3] = 38.00318553314289
 x + s[4] = 3.0056111951265856
 x + s[5] = 31.005338828298388
 x + s[6] = 21.005611195126587
 x + s[7] = 25.00533869746837
 x + s[8] = 12.00533869746837
 x + s[9] = 28.002880666667263
 x + s[10] = 0.002880535837244679
 s[i] ≥ 0 ∀ i ∈ {1,2,…,9,10}
 0 ≤ x ≤ 1

status = Error
x = 0.0028805358372446755
s = [0.000577495, 25.0025, 38.0003, 3.00273, 31.0025, 21.0027, 25.0025, 12.0025, 28.0, 3.46945e-18]
objective = -2.3152680429391075

**Comment by mlubin** [comment]
There's no issue with Ipopt.jl, it correctly reports Ipopt's termination status. Please ask usage questions at https://discourse.julialang.org/.

If you represent the problem as an exponential cone problem with the help of Convex.jl, ECOS doesn't seem to have any trouble on this instance:
```julia
using Convex, ECOS

x = Variable()
s = Variable(10, Positive())

problem = maximize(35.95051084102152 * x + 0.1 * sum(log(v) for v in s),
                   [x + s[1] == 0.0034580308011081798,
                    x + s[2] == 25.005338828298388,
                    x + s[3] == 38.00318553314289,
                    x + s[4] == 3.0056111951265856,
                    x + s[5] == 31.005338828298388,
                    x + s[6] == 21.005611195126587,
                    x + s[7] == 25.00533869746837,
                    x + s[8] == 12.00533869746837,
                    x + s[9] == 28.002880666667263,
                    x + s[10] == 0.002880535837244679])
solve!(problem, ECOSSolver())

@show problem.status
@show problem.optval
```
```
[ deprecation warnings omitted ... ]
ECOS 2.0.5 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  -2.900e+00  +4e+01  1e+00  7e-01  1e+00  1e+00    ---    ---    0  0  - |  -  - 
 1  +5.383e+01  +5.509e+01  +7e+00  8e-01  6e-01  5e+00  2e-01  0.8599  4e-02   1  1  1 |  0  0
 2  +2.400e+01  +2.682e+01  +2e+00  5e-01  4e-01  5e+00  6e-02  0.6689  3e-02   1  1  1 |  0  1
 3  +1.224e+01  +1.326e+01  +9e-01  2e-01  2e-01  2e+00  2e-02  0.7058  9e-02   1  1  1 |  1  1
 4  +5.659e+00  +5.834e+00  +3e-01  5e-02  4e-02  4e-01  7e-03  0.7172  8e-03   1  1  1 |  0  1
 5  +1.408e+00  +1.464e+00  +1e-01  2e-02  1e-02  1e-01  3e-03  0.6072  4e-02   1  1  1 |  1  2
 6  -3.543e-01  -3.336e-01  +5e-02  7e-03  5e-03  5e-02  1e-03  0.6151  2e-02   1  1  1 |  1  2
 7  -8.784e-01  -8.646e-01  +2e-02  4e-03  3e-03  3e-02  6e-04  0.6266  2e-01   1  1  1 |  4  2
 8  -8.497e-01  -8.286e-01  +2e-02  4e-03  3e-03  4e-02  5e-04  0.9791  9e-01   1  1  1 | 16  0
 9  -1.045e+00  -1.034e+00  +9e-03  2e-03  1e-03  2e-02  2e-04  0.6266  1e-01   1  1  1 |  3  2
10  -1.121e+00  -1.116e+00  +4e-03  9e-04  6e-04  9e-03  1e-04  0.9791  5e-01   1  1  1 |  6  0
11  -1.194e+00  -1.192e+00  +1e-03  2e-04  2e-04  2e-03  2e-05  0.7833  3e-02   1  1  1 |  1  1
12  -1.217e+00  -1.217e+00  +2e-04  5e-05  3e-05  5e-04  6e-06  0.7833  2e-02   1  1  0 |  1  1
13  -1.221e+00  -1.221e+00  +5e-05  1e-05  8e-06  1e-04  1e-06  0.7833  9e-03   2  1  0 |  1  1
14  -1.222e+00  -1.222e+00  +2e-05  5e-06  3e-06  5e-05  5e-07  0.6266  6e-02   2  0  0 |  2  2
15  -1.223e+00  -1.223e+00  +5e-06  1e-06  7e-07  1e-05  1e-07  0.7833  1e-02   1  0  0 |  1  1
16  -1.223e+00  -1.223e+00  +1e-06  3e-07  2e-07  3e-06  3e-08  0.7833  5e-02   2  0  0 |  2  1
17  -1.223e+00  -1.223e+00  +8e-08  8e-09  8e-09  8e-08  2e-09  0.9791  1e-02   1  0  0 |  1  0
18  -1.223e+00  -1.223e+00  +4e-08  7e-09  5e-09  8e-08  9e-10  0.3208  4e-01   2  0  0 |  6  5
19  -1.223e+00  -1.223e+00  +2e-08  5e-09  3e-09  6e-08  6e-10  0.4010  2e-01   1  0  0 |  4  4
20  -1.223e+00  -1.223e+00  +5e-09  1e-09  7e-10  1e-08  1e-10  0.7833  9e-03   0  0  0 |  1  1

OPTIMAL (within feastol=1.0e-09, reltol=3.8e-09, abstol=4.6e-09).
Runtime: 0.000618 seconds.
problem.status = :Optimal
problem.optval = 1.2227996376729793
```
You can read more about the exponential cone in this [thesis](https://web.stanford.edu/group/SOL/dissertations/ThesisAkleAdobe-augmented.pdf).

**Comment by MFairley** [comment]
Thanks! I had been using the exponential cone formulation with Convex.jl but I found that Ipopt and Mosek were solving faster so I've been trying to get either of them to work consistently.

**Comment by mlubin** [comment]
@MFairley you may try contacting Mosek support for early access to their new exponential cone solver.
